sudo: required

language: node
node_js:
  - "node"

services:
  - docker

before_script:
  - npm install standard babel-eslint
script: npm run standard-fix

before_install:
  - docker build -t nathejk/chat-server .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker tag nathejk/chat-server:latest nathejk/chat-ser-server:$TRAVIS_BUILD_NUMBER
    docker push nathejk/chat-server;
    fi
