version: "2.1"
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    command: "--smallfiles --logpath=/dev/null"
    restart: always
  chat-server:
    build: .
    command: "node index.js"
    ports:
      - "3002:3002"
    restart: always
    links:
      - mongodb
    depends_on:
      mongodb:
        condition: service_started
    environment:
      PORT: 3002
      NODE_ENV: production
      DB: mongodb
